<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="ZCOBTMH101045-PaolaCastro.local" failures="1" tests="2" name="Command line test" time="1.056" errors="0" timestamp="2022-05-19T19:36:10 COT">
  <testcase classname="com.appiumAutomation.tests.BaseTest" name="@BeforeClass setUp" time="0.46">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:585)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:225)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:79)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:87)
at com.appiumAutomation.tests.BaseTest.setLocalMobileDriver(BaseTest.java:50)
at com.appiumAutomation.tests.BaseTest.setUp(BaseTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: org.openqa.selenium.WebDriverException: Connection refused
Build info: version: '4.1.4', revision: '535d840ee2'
System info: host: 'ZCOBTMH101045-PaolaCastro.local', ip: 'fe80:0:0:0:a3:fae4:e1eb:ecb1%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.3.1', java.version: '11.0.14'
Driver info: driver.version: AppiumDriver
at io.appium.java_client.remote.AppiumCommandExecutor.lambda$execute$4(AppiumCommandExecutor.java:192)
at java.base/java.util.Optional.orElseGet(Optional.java:369)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:191)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
... 42 more
Caused by: java.net.ConnectException: Connection refused
at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass setUp -->
  <testcase classname="com.appiumAutomation.tests.BaseTest" name="@AfterTest tearDown" time="0.0">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.appiumAutomation.tests.BaseTest.tearDown(BaseTest.java:31)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="com.appiumAutomation.tests.FixitTest" name="loginToAppTest" time="0.0">
    <skipped/>
  </testcase> <!-- loginToAppTest -->
  <testcase classname="com.appiumAutomation.tests.FixitTest" name="loginToAppTest" time="0.22">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.appiumAutomation.utils.listeners.TestListener.onTestSkipped(TestListener.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- loginToAppTest -->
  <testcase classname="com.appiumAutomation.tests.BaseTest" name="@AfterTest tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="com.appiumAutomation.tests.BaseTest" name="@AfterTest tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase classname="com.appiumAutomation.tests.FixitTest" name="submitAnIssueTest" time="0.0">
    <ignored/>
  </testcase> <!-- submitAnIssueTest -->
</testsuite> <!-- Command line test -->
